from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from io import BytesIO
from textwrap import wrap

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from app.schemas.supervisor import (
    SupervisorContributionsResponse,
    SupervisorFairnessResponse,
    SupervisorProjectDetailResponse,
)


@dataclass
class SupervisorReportService:
    def build_project_report_pdf(
        self,
        project: SupervisorProjectDetailResponse,
        contributions: SupervisorContributionsResponse,
        fairness: SupervisorFairnessResponse,
    ) -> bytes:
        buffer = BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=A4)

        page_width, page_height = A4
        margin_x = 18 * mm
        y = page_height - (20 * mm)

        y = self._draw_heading(pdf, y)
        y = self._draw_project_summary(pdf, project, fairness, y, margin_x)
        y = self._draw_task_summary(pdf, project, y, margin_x)
        y = self._draw_contributions(pdf, contributions, y, margin_x, page_height)
        y = self._draw_timeline(pdf, project, y, margin_x, page_height)

        y -= 8
        if y < 18 * mm:
            pdf.showPage()
            y = page_height - (20 * mm)
        pdf.setFont("Helvetica-Oblique", 9)
        pdf.setFillColorRGB(0.45, 0.45, 0.45)
        pdf.drawString(margin_x, y, f"Generated by Clovio on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")

        pdf.save()
        buffer.seek(0)
        return buffer.getvalue()

    def _draw_heading(self, pdf: canvas.Canvas, y: float) -> float:
        pdf.setFont("Helvetica-Bold", 18)
        pdf.setFillColorRGB(0.10, 0.10, 0.10)
        pdf.drawString(18 * mm, y, "Clovio Supervisor Report")
        return y - 14

    def _draw_project_summary(
        self,
        pdf: canvas.Canvas,
        project: SupervisorProjectDetailResponse,
        fairness: SupervisorFairnessResponse,
        y: float,
        margin_x: float,
    ) -> float:
        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(margin_x, y, "Project Overview")
        y -= 12

        lines = [
            f"Project Name: {project.name}",
            f"Status: {project.status}",
            f"Risk Level: {project.risk_level}",
            f"Completion: {project.completion_percent:.1f}%",
            f"Fairness Score: {fairness.fairness_score:.1f}/100",
            f"Imbalance Flag: {'Yes' if fairness.imbalance_flag else 'No'}",
        ]
        return self._draw_lines(pdf, lines, y, margin_x)

    def _draw_task_summary(
        self,
        pdf: canvas.Canvas,
        project: SupervisorProjectDetailResponse,
        y: float,
        margin_x: float,
    ) -> float:
        y -= 4
        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(margin_x, y, "Task Summary")
        y -= 12

        lines = [
            f"Tasks Completed: {project.task_completion_done}",
            f"Total Tasks: {project.task_completion_total}",
        ]
        return self._draw_lines(pdf, lines, y, margin_x)

    def _draw_contributions(
        self,
        pdf: canvas.Canvas,
        contributions: SupervisorContributionsResponse,
        y: float,
        margin_x: float,
        page_height: float,
    ) -> float:
        y -= 4
        if y < 22 * mm:
            pdf.showPage()
            y = page_height - (20 * mm)

        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(margin_x, y, "Contribution Breakdown")
        y -= 12

        for item in contributions.contributions:
            if y < 22 * mm:
                pdf.showPage()
                y = page_height - (20 * mm)
            line = (
                f"- {item.name}: {item.contribution_percent:.1f}% | "
                f"Tasks {item.tasks_completed} | Updates {item.updates_count} | "
                f"Activity {item.activity_score:.1f}"
            )
            y = self._draw_lines(pdf, [line], y, margin_x)

        return y

    def _draw_timeline(
        self,
        pdf: canvas.Canvas,
        project: SupervisorProjectDetailResponse,
        y: float,
        margin_x: float,
        page_height: float,
    ) -> float:
        y -= 4
        if y < 22 * mm:
            pdf.showPage()
            y = page_height - (20 * mm)

        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(margin_x, y, "Timeline")
        y -= 12

        timeline_lines = [f"- {item.date}: {item.title} ({item.status})" for item in project.timeline]
        return self._draw_lines(pdf, timeline_lines or ["- No timeline items available"], y, margin_x)

    def _draw_lines(self, pdf: canvas.Canvas, lines: list[str], y: float, margin_x: float) -> float:
        pdf.setFont("Helvetica", 10)
        max_chars = 95
        for line in lines:
            wrapped = wrap(line, width=max_chars) or [""]
            for wrapped_line in wrapped:
                pdf.drawString(margin_x, y, wrapped_line)
                y -= 12
        return y
    
