"""Add completed_at to Task

Revision ID: 10c30b230749
Revises: c1f2a38d4b7c
Create Date: 2026-07-09 21:16:50.281520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c30b230749'
down_revision: Union[str, Sequence[str], None] = 'c1f2a38d4b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversation_participants_id'), 'conversation_participants', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.drop_constraint(op.f('uq_direct_conv'), 'direct_conversations', type_='unique')
    op.create_index(op.f('ix_direct_conversations_id'), 'direct_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_direct_messages_id'), 'direct_messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed_at')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_direct_messages_id'), table_name='direct_messages')
    op.drop_index(op.f('ix_direct_conversations_id'), table_name='direct_conversations')
    op.create_unique_constraint(op.f('uq_direct_conv'), 'direct_conversations', ['user_a_id', 'user_b_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversation_participants_id'), table_name='conversation_participants')
    # ### end Alembic commands ###
