"""Add ContributionLog

Revision ID: 9f29719cc877
Revises: 10c30b230749
Create Date: 2026-07-09 21:23:29.522104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f29719cc877'
down_revision: Union[str, Sequence[str], None] = '10c30b230749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contribution_logs_id'), 'contribution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_contribution_logs_project_id'), 'contribution_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_contribution_logs_task_id'), 'contribution_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_contribution_logs_user_id'), 'contribution_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contribution_logs_user_id'), table_name='contribution_logs')
    op.drop_index(op.f('ix_contribution_logs_task_id'), table_name='contribution_logs')
    op.drop_index(op.f('ix_contribution_logs_project_id'), table_name='contribution_logs')
    op.drop_index(op.f('ix_contribution_logs_id'), table_name='contribution_logs')
    op.drop_table('contribution_logs')
    # ### end Alembic commands ###
